name: diffbot
version: 0.1.1
author: Claudio d'Angelis <claudiodangelis@gmail.com>
description: A Dart client library for Diffbot APIs.
homepage: https://github.com/claudiodangelis/diffbot
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://claudiodangelis.com/docs/diffbot
dependencies:
  http: any
  js: '>=0.2.0 <0.3.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
